# Generated by Django 4.0.1 on 2022-10-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='USERNAME_FIELD',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
