# Generated by Django 4.0.1 on 2022-10-02 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_username_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='USERNAME_FIELD',
        ),
    ]
