# Generated by Django 4.0.1 on 2022-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_remove_user_username_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
