# Generated by Django 4.0.1 on 2022-10-26 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goals', '0003_goal_category_goal_due_date_goal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('text', models.TextField(verbose_name='Текст')),
                ('goal',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                   to='goals.goal', verbose_name='Цель')),
                ('user',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments',
                                   to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
