version: '3.9'

services:

  postgres:
    image: postgres:13.0-alpine
    restart: always
    env_file:
      - .env_locally
    volumes:
      - pg_data_todolist:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d todolist_db" ]
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"
    networks:
      - backend_nw


volumes:
  pg_data_todolist:

networks:
  backend_nw:
    driver: bridge



